[package]
name = "khares"
version = "0.1.0"
edition = "2021"

[dependencies]
# Required FF for json support
rocket = { version = "0.5.0", features = ["json"] }

# Avoids extra annotation over serializable structs
serde = { version = "1.0", features = ["derive"] }
mongodb = "2.8.1"
log = "0.4.21"